### ISSUE TITLE
"actual override" functions not merged in html output

### ISSUE THREAD

**Issue by Znerole** [orangy/dokka#2094]
**Describe the bug**
In a Kotlin Multiplatform Mobile project, when I'm having an interface implemented by an "expect" class, the HTML output correctly merges properties into a single item in the documentation, but fails to do so for functions.

Example:
```kotlin
// in commonMain
interface MyInterface {
    /** Properly merged across targets in documentation! */
    val justAValue: String
    /** Not merged in documentation! */
    fun justAFunction()
}

expect class MyClass : MyInterface {
    override val justAValue: String
    override fun justAFunction()
}


// in androidMain and iosMain
actual class MyClass : MyInterface {
    actual override val justAValue: String = "abc"
    actual override fun justAFunction() {}
}
```

**Expected behaviour**
I would expect in the documentation of `MyClass` to see one entry for the function `justAFunction()`, possibly with three different flavors (common, android, ios). For the property `justAValue` this works as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/6444999/130925513-c6571c0a-2281-469d-b139-c89e6dfecaad.png)

![image](https://user-images.githubusercontent.com/6444999/130925574-fc0f4203-6ab2-4dd6-8a76-45a477a5f485.png)

**To Reproduce**
I have a primitive example project which is based on the Android Studio wizard for KMM applications:
[DokkaTest.zip](https://github.com/Kotlin/dokka/files/7052633/DokkaTest.zip)

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v6.7.1
- Dokka version: 1.5.0

**Are you willing to provide a PR?**
I'm afraid not.

**Comment by atyrin** [comment]
The same problem exists for types if there is a KDoc.

```Kotlin
// Common code
/**
 * Summary of Common Platform
 */
expect class Platform

// Native and JS
actual class Platform

// JVM
/**
 * JVM Platform
 */
actual class Platform
```

as result types without KDoc are merged in the table, others are splitter

![image](https://user-images.githubusercontent.com/7689049/132362559-61470813-809e-41f9-bd5e-9ce52d65400f.png)
