### ISSUE TITLE
StackOverflowError on kotlin multiplatform module dokkaHtmlMultimodule

### ISSUE THREAD

**Issue by yamilmedina** [orangy/dokka#2853]
**Describe the bug**
We are working on a Kotlin multiplatform project and been using Dokka for our documentation since the beginning, but now we are having issues as the project grew. Specifically, a `StackOverflowError` error leading to a failure.

**Expected behaviour**
We can execute `dokkaHtmlMultimodule` without OOM exceptions.

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
You can have a look into our ghactions execution. 
https://github.com/wireapp/kalium/actions/runs/4136039323/jobs/7149323719

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
tasks.withType(AbstractDokkaLeafTask::class.java).configureEach {
        dokkaSourceSets.configureEach {
            file("module.md").takeIf { it.exists() }?.let {
                includes.from(it)
            }
            includes.from(rootProject.file("dokka/moduledoc.md").path)
            samples.from(rootProject.file("samples"))
            includeNonPublic.set(true)
            documentedVisibilities.set(listOf(Visibility.PUBLIC, Visibility.INTERNAL))
       }
 }      
```

You can have a look, as the project is opensource into: https://github.com/wireapp/kalium/blob/develop/buildSrc/src/main/kotlin/com/wire/kalium/plugins/CommonDokkaConfig.kt

**Installation**
- Operating system: macOS 12
- Build tool: Gradle v7.5.1
- Dokka version: 1.7.20

**Additional context**
The specific target failing is always` :network:compileCommonMainKotlinMetadata` if I run locally 2 things can provide more info:
- When executed with --stacktrace we get a:` java.lang.StackOverflowError` underneath.
- If we run the task to generate docs for a module with fewer dependencies, example just the same `:network:dokkaHtmlPartial` the documentation succeeds.
- Also I tried some of the things mentioned here https://github.com/Kotlin/dokka/issues/1405 without success.

**Are you willing to provide a PR?**
Yes

**Comment by yamilmedina** [comment]
I'm closing this one as we brought it back, with the help of using: 

> cacheRoot.set(file("default"))

and setting and explicit classpath dependency

> classpath.from(file("location of dependency"))

Thanks anyway for the help and pointers, was useful to gather more debugging insights @IgnatBeresnev

**Comment by IgnatBeresnev** [comment]
> cacheRoot.set(file("default"))

It's interesting that it helped because this configuration property is not used by Dokka at all, as far as I know 😅 

But I'm glad you were able to resolve it
