### ISSUE TITLE
[K2] KDoc links for extensions are unresolved

### ISSUE THREAD

**Issue by vmishenev** [orangy/dokka#3234]
It results that generated documentation has plain text instead of a link to an extension , e.g. `[A.someExtension()]`.
It is blocked by  [KTIJ-25454](https://youtrack.jetbrains.com/issue/KTIJ-25454/K2-IDE-Unresolved-extension-functions-in-KDoc)

**Comment by IgnatBeresnev** [comment]
Note: add some basic tests for extensions

**Comment by IgnatBeresnev** [comment]
The upstream issue has been fixed, so we are not blocked now

**Comment by IgnatBeresnev** [comment]
This has been unblocked and fixed upstream, just need to check it and write a test

**Comment by atyrin** [comment]
There is still a difference in K1 and K2 with references like `[A.someExtension()]`
K1
<img width="704" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/43381dfe-42f4-4205-ad06-6d2b234bdbbc">
K2
<img width="712" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/6a47d20f-33e6-4811-a384-18503c897b6f">

But K1 reference leads to the same page as receiver.
